package epam.students.prihodii;

public enum CardType {

    SCHOOL_TEN_DAYS,
    SCHOOL_MONTH,
    STUDENT_TEN_DAYS,
    STUDENT_MONTH,
    ADULT_TEN_DAYS,
    ADULT_MONTH,

    SCHOOL_FIVE_TRIPS,
    SCHOOL_TEN_TRIPS,
    STUDENT_FIVE_TRIPS,
    STUDENT_TEN_TRIPS,
    ADULT_FIVE_TRIPS,
    ADULT_TEN_TRIPS,

    ADULT_MONEY_CARD;
}
